name: Terraform (deploy)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # REQUIRED for OIDC

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Azure login using OIDC
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:        ${{ vars.AZURE_CLIENT_ID }}
          tenant-id:        ${{ vars.AZURE_TENANT_ID }}
          subscription-id:  ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      # 4. Terraform Init / Plan / Apply
      - name: Terraform Init, Plan, and Apply
        shell: bash
        run: |
          set -euo pipefail
          cd infra/envs/dev
          terraform init -backend-config=backend.hcl
          terraform plan -out=tfplan.bin
          terraform apply -auto-approve tfplan.bin
